#!/bin/bash

chmod +x scripts/setbg

rm -rf ~/.config/alacritty; mv .config/* ~/.config
rm -rf ~/.xinitrc ~/.zshrc; mv scripts/.xinitrc scripts/.zshrc ~/

mkdir bin
cd bin
git clone https://git.suckless.org/dwm --quiet; printf "\033[1;33mInstalled dwm\033[1;0m"
git clone https://git.suckless.org/slstatus --quiet; printf "\033[1;33mInstalled slstatus\033[1;0m"

cd dwm
rm -f dwm.c; rm -f config.def.h
cd ../slstatus
rm -f config.def.h

cd ../..
mv bin/dwm/* dwm/
mv bin/slstatus/* slstatus

rm -rf bin

cd dwm; sudo make clean install
cd ../slstatus; sudo make clean install

cd ..

printf "\033[1;32mCompleted!\033[1;0m"
