#!/bin/bash

clear

# Change Shell
chsh -s /usr/bin/zsh; clear

printf "\033[1;34mInstalling...\033[1;0m\n"

# Management of background script
chmod +x scripts/setbg

# Remove any previous configuration
rm -rf ~/.xinitrc ~/.zshrc
if [ -d "~/.config" ];
then
    rm -rf ~/.config/alacritty ~/.config/rofi
else
    mkdir ~/.config
fi

# Plugin Manager Directory
if [ ! -d "~/.local/lib/deadbeef" ];
then
    mkdir -p ~/.local/lib/deadbeef
fi

# Move script/config files to their proper locations
sudo mv scripts/setbg /usr/local/bin
mv config/.xinitrc config/.zshrc ~/
mv config/* ~/.config

# Deadbeef Plugin Installation
/usr/bin/install -v -c -m 644 ./scripts/ddb_misc_quick_search_GTK3.so ${HOME}/.local/lib/deadbeef/

# Make xinitrc executable
chmod +x ~/.xinitrc

# Make Application Launcher theme executable
chmod +x ~/.config/rofi/launchers/text/launcher
sudo cp ~/.config/rofi/launchers/text/launcher /usr/local/bin/rofiThemeLauncher

# Removal of empty directories
rm -rf config scripts

# Compile dwm and slstatus
cd dwm; sudo make clean install > /dev/null
cd ../slstatus; sudo make clean install > /dev/null

# Display Manager
sudo systemctl enable ly.service

printf "Reboot the system for any changes to take place.\n"

