#!/bin/bash

clear

# Change Shell
chsh -s /usr/bin/zsh

clear

printf "\033[1;34mInstalling...\033[1;0m\n"

# Allow the bgscript to be executable
chmod +x scripts/setbg

# Remove any previous configuration
if [ -d ~/.config ];
    rm -rf ~/.xinitrc ~/.zshrc
    rm -rf ~/.config/alacritty ~/.config/rofi
else
    mkdir ~/.config
fi

# Move config files to their correct spot
mv .config/* ~/.config
mv scripts/.xinitrc scripts/.zshrc ~/

# Make xinitrc executable
chmod +x ~/.xinitrc

# Make Application Launcher theme executable
chmod +x ~/.config/rofi/launchers/text/launcher
sudo cp ~/.config/rofi/launchers/text/launcher /usr/local/bin/rofiThemeLauncher

rm -rf .config

# Donwload dwm as well as slstatus in a new folder
mkdir bin
cd bin
git clone https://git.suckless.org/dwm --quiet; printf "\033[1;33mInstalled dwm\033[1;0m\n"
git clone https://git.suckless.org/slstatus --quiet; printf "\033[1;33mInstalled slstatus\033[1;0m\n"

# Merge dwm files
cd dwm
rm -f dwm.c; rm -f config.def.h
cd ../slstatus
rm -f config.def.h

# Merge slstatus files
cd ../..
mv bin/dwm/* dwm/
mv bin/slstatus/* slstatus

# Remove the folder which previously had the 
# fresh install of dwm and slstatus
rm -rf bin

# Compile dwm and slstatus
cd dwm; sudo make clean install > /dev/null
cd ../slstatus; sudo make clean install > /dev/null

cd ..

# Display Manager
systemctl enable ly.service

printf "\033[1;32mCompleted!\033[1;0m\n"

sleep 1; clear

printf "Reboot the system for any changes to take place."
